<?php

namespace controlBundle\Repository;

/**
 * alumnoCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class alumnoCursoRepository extends \Doctrine\ORM\EntityRepository
{
}
