<?php

namespace controlBundle\Repository;

/**
 * cursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cursoRepository extends \Doctrine\ORM\EntityRepository
{
}
