<?php

namespace controlBundle\Repository;

/**
 * historialActuacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class historialActuacionesRepository extends \Doctrine\ORM\EntityRepository
{
}
