<?php

namespace controlBundle\Repository;

/**
 * profesorCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class profesorCursoRepository extends \Doctrine\ORM\EntityRepository
{
}
